// All workout plans from trainer
export const WORKOUT_PLANS = {
  day1: {
    label: 'Day 1',
    name: 'Chest & Triceps',
    shortName: 'Chest/Tri',
    muscleGroups: ['Chest', 'Triceps'],
    color: '#f97316',
    icon: 'chest',
    exercises: [
      { id: 'flat_bench_rod', name: 'Flat Bench (Rod)', defaultSets: 3, defaultReps: 10, unit: 'kg' },
      { id: 'inclined_db_press', name: 'Inclined DB Press', defaultSets: 3, defaultReps: 10, unit: 'kg' },
      { id: 'high_low_cable_fly', name: 'High to Low Cable Fly', defaultSets: 3, defaultReps: 12, unit: 'kg' },
      { id: 'chest_press_machine', name: 'Chest Press Machine', defaultSets: 3, defaultReps: 10, unit: 'kg' },
      { id: 'pec_deck_flys', name: 'Pec Deck Flys', defaultSets: 3, defaultReps: 12, unit: 'kg' },
      { id: 'tricep_pressdown', name: 'Triceps Press Down', defaultSets: 3, defaultReps: 12, unit: 'kg' },
      { id: 'overhead_extension', name: 'Overhead Extension', defaultSets: 3, defaultReps: 12, unit: 'kg' },
      { id: 'heavy_db_kickback', name: 'Heavy DB + DB Kickback', defaultSets: 3, defaultReps: 12, unit: 'kg' },
    ],
  },
  day2: {
    label: 'Day 2',
    name: 'Back & Biceps',
    shortName: 'Back/Bi',
    muscleGroups: ['Back', 'Biceps'],
    color: '#3b82f6',
    icon: 'back',
    exercises: [
      { id: 'lat_pulldown', name: 'Lats Pull Down', defaultSets: 3, defaultReps: 10, unit: 'kg' },
      { id: 'db_rowing', name: 'DB Rowing', defaultSets: 3, defaultReps: 10, unit: 'kg' },
      { id: 'seated_rowing', name: 'Seated Rowing', defaultSets: 3, defaultReps: 10, unit: 'kg' },
      { id: 'v_cut_pulling', name: 'V-Cut Pulling', defaultSets: 3, defaultReps: 12, unit: 'kg' },
      { id: 'bend_over_rod_rowing', name: 'Bend Over Rod Rowing', defaultSets: 3, defaultReps: 10, unit: 'kg' },
      { id: 'bicep_rod', name: 'Bicep Rod', defaultSets: 3, defaultReps: 12, unit: 'kg' },
      { id: 'db_curls', name: 'DB Curls', defaultSets: 3, defaultReps: 12, unit: 'kg' },
      { id: 'hammer_rope', name: 'Hammer Rope', defaultSets: 3, defaultReps: 12, unit: 'kg' },
    ],
  },
  day3: {
    label: 'Day 3',
    name: 'Shoulders & Legs',
    shortName: 'Shld/Legs',
    muscleGroups: ['Shoulders', 'Legs'],
    color: '#10b981',
    icon: 'shoulders',
    exercises: [
      { id: 'front_shoulder_press_rod', name: 'Front Shoulder Press (Rod)', defaultSets: 3, defaultReps: 10, unit: 'kg' },
      { id: 'db_press_seated', name: 'DB Press Seated', defaultSets: 3, defaultReps: 10, unit: 'kg' },
      { id: 'db_lateral_fly', name: 'DB Lateral Fly', defaultSets: 3, defaultReps: 12, unit: 'kg' },
      { id: 'upright_row_neck_rod', name: 'Upright Row (Neck Rod)', defaultSets: 3, defaultReps: 12, unit: 'kg' },
      { id: 'face_pulls', name: 'Face Pulls', defaultSets: 3, defaultReps: 15, unit: 'kg' },
      { id: 'db_shrugs_arnold', name: 'DB Shrugs + Arnold Press', defaultSets: 3, defaultReps: 12, unit: 'kg' },
      { id: 'weighted_squats', name: 'Weighted Squats', defaultSets: 3, defaultReps: 10, unit: 'kg' },
      { id: 'leg_press', name: 'Leg Press', defaultSets: 3, defaultReps: 12, unit: 'kg' },
      { id: 'leg_extension', name: 'Leg Extension', defaultSets: 3, defaultReps: 12, unit: 'kg' },
      { id: 'sumo_squats', name: 'Sumo Squats', defaultSets: 3, defaultReps: 12, unit: 'kg' },
    ],
  },
  day4: {
    label: 'Day 4',
    name: 'Upper Body (Giant Set)',
    shortName: 'Upper',
    muscleGroups: ['Upper Body'],
    color: '#ef4444',
    icon: 'upper',
    exercises: [
      { id: 'flat_db_press', name: 'Flat DB Press', defaultSets: 3, defaultReps: 10, unit: 'kg' },
      { id: 'lat_pulldown_giant', name: 'Lats Pull Down', defaultSets: 3, defaultReps: 10, unit: 'kg' },
      { id: 'shoulder_db_flys', name: 'Shoulder DB Flys', defaultSets: 3, defaultReps: 12, unit: 'kg' },
      { id: 'bicep_curls_giant', name: 'Bicep Curls (Rod/DB/Cable)', defaultSets: 3, defaultReps: 12, unit: 'kg' },
      { id: 'tricep_pressdown_giant', name: 'Triceps Press Down', defaultSets: 3, defaultReps: 12, unit: 'kg' },
      { id: 'deadlift', name: 'Deadlift', defaultSets: 3, defaultReps: 8, unit: 'kg' },
    ],
  },
  day5: {
    label: 'Day 5',
    name: 'Lower Body',
    shortName: 'Lower',
    muscleGroups: ['Legs'],
    color: '#8b5cf6',
    icon: 'legs',
    exercises: [
      { id: 'leg_extension_lower', name: 'Leg Extension', defaultSets: 3, defaultReps: 12, unit: 'kg' },
      { id: 'lunges', name: 'Lunges', defaultSets: 3, defaultReps: 12, unit: 'kg' },
      { id: 'goblet_squats', name: 'Goblet Squats', defaultSets: 3, defaultReps: 12, unit: 'kg' },
      { id: 'leg_curls', name: 'Leg Curls', defaultSets: 3, defaultReps: 12, unit: 'kg' },
      { id: 'rdl_db', name: "RDL's DB", defaultSets: 3, defaultReps: 10, unit: 'kg' },
      { id: 'calf_raises_seated', name: 'Calf Raises Seated', defaultSets: 3, defaultReps: 15, unit: 'bodyweight' },
      { id: 'calf_raises_standing', name: 'Calf Raises Standing', defaultSets: 3, defaultReps: 15, unit: 'bodyweight' },
    ],
  },
  day6: {
    label: 'Day 6',
    name: 'Cardio & Mobility',
    shortName: 'Cardio',
    muscleGroups: ['Cardio'],
    color: '#ec4899',
    icon: 'cardio',
    exercises: [
      { id: 'treadmill', name: 'Treadmill / Running', defaultSets: 1, defaultReps: 1, unit: 'min' },
      { id: 'cycling', name: 'Cycling / Elliptical', defaultSets: 1, defaultReps: 1, unit: 'min' },
      { id: 'stretching', name: 'Stretching', defaultSets: 1, defaultReps: 1, unit: 'min' },
      { id: 'foam_rolling', name: 'Foam Rolling', defaultSets: 1, defaultReps: 1, unit: 'min' },
      { id: 'yoga_mobility', name: 'Yoga / Mobility', defaultSets: 1, defaultReps: 1, unit: 'min' },
    ],
  },
}

export const DAY_ORDER = ['day1', 'day2', 'day3', 'day4', 'day5', 'day6']

// Muscle group mapping for exercises (used in analysis)
export const MUSCLE_GROUP_MAP = {
  // Chest
  flat_bench_rod: 'Chest', inclined_db_press: 'Chest', high_low_cable_fly: 'Chest',
  chest_press_machine: 'Chest', pec_deck_flys: 'Chest', flat_db_press: 'Chest',
  // Triceps
  tricep_pressdown: 'Triceps', overhead_extension: 'Triceps', heavy_db_kickback: 'Triceps',
  tricep_pressdown_giant: 'Triceps',
  // Back
  lat_pulldown: 'Back', db_rowing: 'Back', seated_rowing: 'Back', v_cut_pulling: 'Back',
  bend_over_rod_rowing: 'Back', lat_pulldown_giant: 'Back', deadlift: 'Back',
  // Biceps
  bicep_rod: 'Biceps', db_curls: 'Biceps', hammer_rope: 'Biceps', bicep_curls_giant: 'Biceps',
  // Shoulders
  front_shoulder_press_rod: 'Shoulders', db_press_seated: 'Shoulders', db_lateral_fly: 'Shoulders',
  upright_row_neck_rod: 'Shoulders', face_pulls: 'Shoulders', db_shrugs_arnold: 'Shoulders',
  shoulder_db_flys: 'Shoulders',
  // Legs
  weighted_squats: 'Legs', leg_press: 'Legs', leg_extension: 'Legs', sumo_squats: 'Legs',
  leg_extension_lower: 'Legs', lunges: 'Legs', goblet_squats: 'Legs', leg_curls: 'Legs',
  rdl_db: 'Legs', calf_raises_seated: 'Legs', calf_raises_standing: 'Legs',
  // Cardio
  treadmill: 'Cardio', cycling: 'Cardio', stretching: 'Cardio',
  foam_rolling: 'Cardio', yoga_mobility: 'Cardio',
}

// Historical data pre-loaded
export const HISTORICAL_LOGS = [
  {
    date: '2026-05-15',
    dayKey: 'day1',
    completed: true,
    exercises: [
      { id: 'flat_bench_rod', name: 'Flat Bench (Rod)', sets: [{ weight: 7.5, reps: 10, done: true }, { weight: 7.5, reps: 10, done: true }, { weight: 7.5, reps: 10, done: true }] },
      { id: 'inclined_db_press', name: 'Inclined DB Press', sets: [{ weight: 7.5, reps: 10, done: true }, { weight: 7.5, reps: 10, done: true }, { weight: 7.5, reps: 10, done: true }] },
      { id: 'high_low_cable_fly', name: 'High to Low Cable Fly', sets: [{ weight: 14.5, reps: 12, done: true }, { weight: 14.5, reps: 12, done: true }, { weight: 14.5, reps: 12, done: true }] },
      { id: 'pec_deck_flys', name: 'Pec Deck Flys', sets: [{ weight: 20, reps: 12, done: true }, { weight: 20, reps: 12, done: true }, { weight: 25, reps: 12, done: true }] },
      { id: 'tricep_pressdown', name: 'Triceps Press Down', sets: [{ weight: 24.5, reps: 12, done: true }, { weight: 24.5, reps: 12, done: true }, { weight: 24.5, reps: 12, done: true }] },
      { id: 'overhead_extension', name: 'Overhead Extension', sets: [{ weight: 18.5, reps: 12, done: true }, { weight: 18.5, reps: 12, done: true }, { weight: 18.5, reps: 12, done: true }] },
      { id: 'heavy_db_kickback', name: 'Heavy DB + DB Kickback', sets: [{ weight: 7.5, reps: 12, done: true }, { weight: 7.5, reps: 12, done: true }, { weight: 7.5, reps: 12, done: true }] },
    ],
  },
  {
    date: '2026-05-16',
    dayKey: 'day2',
    completed: true,
    exercises: [
      { id: 'lat_pulldown', name: 'Lats Pull Down', sets: [{ weight: 30, reps: 10, done: true }, { weight: 30, reps: 10, done: true }, { weight: 30, reps: 10, done: true }] },
      { id: 'db_rowing', name: 'DB Rowing', sets: [{ weight: 7.5, reps: 10, done: true }, { weight: 7.5, reps: 10, done: true }, { weight: 7.5, reps: 10, done: true }] },
      { id: 'seated_rowing', name: 'Seated Rowing', sets: [{ weight: 57, reps: 10, done: true }, { weight: 57, reps: 10, done: true }, { weight: 57, reps: 10, done: true }] },
      { id: 'v_cut_pulling', name: 'V-Cut Pulling', sets: [{ weight: 57, reps: 12, done: true }, { weight: 57, reps: 12, done: true }, { weight: 57, reps: 12, done: true }] },
      { id: 'bicep_rod', name: 'Bicep Rod', sets: [{ weight: 5, reps: 12, done: true }, { weight: 5, reps: 12, done: true }, { weight: 5, reps: 12, done: true }] },
    ],
  },
  {
    date: '2026-05-18',
    dayKey: 'day1',
    completed: true,
    exercises: [
      { id: 'flat_bench_rod', name: 'Flat Bench (Rod)', sets: [{ weight: 7.5, reps: 10, done: true }, { weight: 7.5, reps: 10, done: true }, { weight: 7.5, reps: 10, done: true }] },
      { id: 'inclined_db_press', name: 'Inclined DB Press', sets: [{ weight: 7.5, reps: 10, done: true }, { weight: 7.5, reps: 10, done: true }, { weight: 7.5, reps: 10, done: true }] },
      { id: 'high_low_cable_fly', name: 'High to Low Cable Fly', sets: [{ weight: 14.5, reps: 12, done: true }, { weight: 14.5, reps: 12, done: true }, { weight: 14.5, reps: 12, done: true }] },
      { id: 'pec_deck_flys', name: 'Pec Deck Flys', sets: [{ weight: 25, reps: 12, done: true }, { weight: 25, reps: 12, done: true }, { weight: 25, reps: 12, done: true }] },
      { id: 'tricep_pressdown', name: 'Triceps Press Down', sets: [{ weight: 24.5, reps: 12, done: true }, { weight: 24.5, reps: 12, done: true }, { weight: 24.5, reps: 12, done: true }] },
      { id: 'overhead_extension', name: 'Overhead Extension', sets: [{ weight: 18.5, reps: 12, done: true }, { weight: 18.5, reps: 12, done: true }, { weight: 18.5, reps: 12, done: true }] },
      { id: 'heavy_db_kickback', name: 'Heavy DB + DB Kickback', sets: [{ weight: 7.5, reps: 12, done: true }, { weight: 7.5, reps: 12, done: true }, { weight: 7.5, reps: 12, done: true }] },
    ],
  },
  {
    date: '2026-05-19',
    dayKey: 'day2',
    completed: true,
    exercises: [
      { id: 'lat_pulldown', name: 'Lats Pull Down', sets: [{ weight: 30, reps: 10, done: true }, { weight: 30, reps: 10, done: true }, { weight: 30, reps: 10, done: true }] },
      { id: 'db_rowing', name: 'DB Rowing', sets: [{ weight: 7.5, reps: 10, done: true }, { weight: 7.5, reps: 10, done: true }, { weight: 7.5, reps: 10, done: true }] },
      { id: 'seated_rowing', name: 'Seated Rowing', sets: [{ weight: 57, reps: 10, done: true }, { weight: 57, reps: 10, done: true }, { weight: 57, reps: 10, done: true }] },
      { id: 'v_cut_pulling', name: 'V-Cut Pulling', sets: [{ weight: 57, reps: 12, done: true }, { weight: 57, reps: 12, done: true }, { weight: 57, reps: 12, done: true }] },
      { id: 'bicep_rod', name: 'Bicep Rod', sets: [{ weight: 5, reps: 12, done: true }, { weight: 5, reps: 12, done: true }, { weight: 5, reps: 12, done: true }] },
      { id: 'hammer_rope', name: 'Hammer Rope', sets: [{ weight: 24.5, reps: 12, done: true }, { weight: 24.5, reps: 12, done: true }, { weight: 24.5, reps: 12, done: true }] },
    ],
  },
  {
    date: '2026-05-20',
    dayKey: 'day3',
    completed: true,
    exercises: [
      { id: 'front_shoulder_press_rod', name: 'Front Shoulder Press (Rod)', sets: [{ weight: 0, reps: 10, done: true }, { weight: 2.5, reps: 10, done: true }, { weight: 2.5, reps: 10, done: true }] },
      { id: 'db_press_seated', name: 'DB Press Seated', sets: [{ weight: 7.5, reps: 10, done: true }, { weight: 7.5, reps: 10, done: true }, { weight: 7.5, reps: 10, done: true }] },
      { id: 'db_lateral_fly', name: 'DB Lateral Fly', sets: [{ weight: 5, reps: 12, done: true }, { weight: 5, reps: 12, done: true }, { weight: 5, reps: 12, done: true }] },
      { id: 'upright_row_neck_rod', name: 'Upright Row (Neck Rod)', sets: [{ weight: 0, reps: 10, done: true }, { weight: 2.5, reps: 10, done: true }, { weight: 2.5, reps: 10, done: true }] },
      { id: 'face_pulls', name: 'Face Pulls', sets: [{ weight: 18.5, reps: 15, done: true }, { weight: 18.5, reps: 15, done: true }, { weight: 18.5, reps: 15, done: true }] },
      { id: 'db_shrugs_arnold', name: 'DB Shrugs + Arnold Press', sets: [{ weight: 7.5, reps: 12, done: true }, { weight: 7.5, reps: 12, done: true }, { weight: 7.5, reps: 12, done: true }] },
      { id: 'weighted_squats', name: 'Weighted Squats', sets: [{ weight: 10, reps: 10, done: true }, { weight: 10, reps: 10, done: true }, { weight: 10, reps: 10, done: true }] },
      { id: 'leg_press', name: 'Leg Press', sets: [{ weight: 15, reps: 12, done: true }, { weight: 15, reps: 12, done: true }] },
      { id: 'leg_extension', name: 'Leg Extension', sets: [{ weight: 35, reps: 12, done: true }, { weight: 35, reps: 12, done: true }] },
      { id: 'sumo_squats', name: 'Sumo Squats', sets: [{ weight: 7.5, reps: 12, done: true }, { weight: 7.5, reps: 12, done: true }] },
    ],
  },
  {
    date: '2026-05-21',
    dayKey: 'day4',
    completed: true,
    exercises: [
      { id: 'flat_db_press', name: 'Flat DB Press', sets: [{ weight: 5, reps: 10, done: true }, { weight: 7.5, reps: 10, done: true }, { weight: 10, reps: 10, done: true }] },
      { id: 'lat_pulldown_giant', name: 'Lats Pull Down', sets: [{ weight: 25, reps: 10, done: true }, { weight: 30, reps: 10, done: true }, { weight: 35, reps: 10, done: true }] },
      { id: 'shoulder_db_flys', name: 'Shoulder DB Flys', sets: [{ weight: 5, reps: 12, done: true }, { weight: 7.5, reps: 12, done: true }, { weight: 10, reps: 12, done: true }] },
      { id: 'bicep_curls_giant', name: 'Bicep Curls (Rod/DB/Cable)', sets: [{ weight: 5, reps: 12, done: true }, { weight: 7.5, reps: 12, done: true }, { weight: 10, reps: 12, done: true }] },
      { id: 'tricep_pressdown_giant', name: 'Triceps Press Down', sets: [{ weight: 0, reps: 12, done: true }, { weight: 0, reps: 12, done: true }, { weight: 0, reps: 12, done: true }] },
      { id: 'deadlift', name: 'Deadlift', sets: [{ weight: 0, reps: 8, done: true }, { weight: 2.5, reps: 8, done: true }, { weight: 5, reps: 8, done: true }] },
    ],
  },
  {
    date: '2026-05-24',
    dayKey: 'day5',
    completed: true,
    exercises: [
      { id: 'leg_extension_lower', name: 'Leg Extension', sets: [{ weight: 35, reps: 12, done: true }, { weight: 35, reps: 12, done: true }, { weight: 35, reps: 12, done: true }] },
      { id: 'lunges', name: 'Lunges', sets: [{ weight: 5, reps: 12, done: true }, { weight: 7.5, reps: 12, done: true }, { weight: 7.5, reps: 12, done: true }, { weight: 7.5, reps: 12, done: true }] },
      { id: 'goblet_squats', name: 'Goblet Squats', sets: [{ weight: 7.5, reps: 12, done: true }, { weight: 7.5, reps: 12, done: true }, { weight: 7.5, reps: 12, done: true }] },
      { id: 'leg_curls', name: 'Leg Curls', sets: [{ weight: 35, reps: 12, done: true }, { weight: 40, reps: 12, done: true }, { weight: 40, reps: 12, done: true }] },
      { id: 'rdl_db', name: "RDL's DB", sets: [{ weight: 7.5, reps: 10, done: true }, { weight: 7.5, reps: 10, done: true }, { weight: 10, reps: 10, done: true }] },
    ],
  },
  {
    date: '2026-05-25',
    dayKey: 'day1',
    completed: true,
    exercises: [
      { id: 'flat_bench_rod', name: 'Flat Bench (Rod)', sets: [{ weight: 7.5, reps: 10, done: true }, { weight: 7.5, reps: 10, done: true }, { weight: 7.5, reps: 10, done: true }] },
      { id: 'inclined_db_press', name: 'Inclined DB Press', sets: [{ weight: 7.5, reps: 10, done: true }, { weight: 7.5, reps: 10, done: true }, { weight: 7.5, reps: 10, done: true }] },
      { id: 'high_low_cable_fly', name: 'High to Low Cable Fly', sets: [{ weight: 19.5, reps: 12, done: true }, { weight: 19.5, reps: 12, done: true }, { weight: 19.5, reps: 12, done: true }] },
      { id: 'pec_deck_flys', name: 'Pec Deck Flys', sets: [{ weight: 25, reps: 12, done: true }, { weight: 25, reps: 12, done: true }, { weight: 30, reps: 12, done: true }] },
      { id: 'tricep_pressdown', name: 'Triceps Press Down', sets: [{ weight: 24.5, reps: 12, done: true }, { weight: 24.5, reps: 12, done: true }, { weight: 29.5, reps: 12, done: true }] },
      { id: 'overhead_extension', name: 'Overhead Extension', sets: [{ weight: 18.5, reps: 12, done: true }, { weight: 18.5, reps: 12, done: true }, { weight: 18.5, reps: 12, done: true }] },
      { id: 'heavy_db_kickback', name: 'Heavy DB + DB Kickback', sets: [{ weight: 7.5, reps: 12, done: true }, { weight: 7.5, reps: 12, done: true }, { weight: 7.5, reps: 12, done: true }] },
    ],
  },
  {
    date: '2026-05-26',
    dayKey: 'day2',
    completed: true,
    exercises: [
      { id: 'lat_pulldown', name: 'Lats Pull Down', sets: [{ weight: 30, reps: 10, done: true }, { weight: 30, reps: 10, done: true }, { weight: 30, reps: 10, done: true }] },
      { id: 'seated_rowing', name: 'Seated Rowing', sets: [{ weight: 57, reps: 10, done: true }, { weight: 57, reps: 10, done: true }, { weight: 57, reps: 10, done: true }] },
      { id: 'v_cut_pulling', name: 'V-Cut Pulling', sets: [{ weight: 57, reps: 12, done: true }, { weight: 57, reps: 12, done: true }, { weight: 57, reps: 12, done: true }] },
      { id: 'bend_over_rod_rowing', name: 'Bend Over Rod Rowing', sets: [{ weight: 2.5, reps: 10, done: true }, { weight: 2.5, reps: 10, done: true }, { weight: 2.5, reps: 10, done: true }] },
      { id: 'bicep_rod', name: 'Bicep Rod', sets: [{ weight: 5, reps: 12, done: true }, { weight: 5, reps: 12, done: true }, { weight: 5, reps: 12, done: true }] },
      { id: 'db_curls', name: 'DB Curls', sets: [{ weight: 7.5, reps: 12, done: true }, { weight: 7.5, reps: 12, done: true }, { weight: 7.5, reps: 12, done: true }] },
      { id: 'hammer_rope', name: 'Hammer Rope', sets: [{ weight: 19.5, reps: 12, done: true }, { weight: 19.5, reps: 12, done: true }, { weight: 19.5, reps: 12, done: true }] },
    ],
  },
  {
    date: '2026-05-27',
    dayKey: 'day3',
    completed: true,
    exercises: [
      { id: 'front_shoulder_press_rod', name: 'Front Shoulder Press (Rod)', sets: [{ weight: 2.5, reps: 10, done: true }, { weight: 2.5, reps: 10, done: true }, { weight: 5, reps: 10, done: true }] },
      { id: 'db_press_seated', name: 'DB Press Seated', sets: [{ weight: 7.5, reps: 10, done: true }, { weight: 7.5, reps: 10, done: true }, { weight: 7.5, reps: 10, done: true }] },
      { id: 'db_lateral_fly', name: 'DB Lateral Fly', sets: [{ weight: 5, reps: 12, done: true }, { weight: 5, reps: 12, done: true }, { weight: 7.5, reps: 12, done: true }] },
      { id: 'upright_row_neck_rod', name: 'Upright Row (Neck Rod)', sets: [{ weight: 2.5, reps: 10, done: true }, { weight: 2.5, reps: 10, done: true }, { weight: 2.5, reps: 10, done: true }] },
      { id: 'face_pulls', name: 'Face Pulls', sets: [{ weight: 18.5, reps: 15, done: true }, { weight: 18.5, reps: 15, done: true }, { weight: 18.5, reps: 15, done: true }] },
      { id: 'db_shrugs_arnold', name: 'DB Shrugs + Arnold Press', sets: [{ weight: 7.5, reps: 12, done: true }, { weight: 7.5, reps: 12, done: true }, { weight: 7.5, reps: 12, done: true }] },
      { id: 'weighted_squats', name: 'Weighted Squats', sets: [{ weight: 10, reps: 10, done: true }, { weight: 10, reps: 10, done: true }, { weight: 10, reps: 10, done: true }] },
      { id: 'leg_press', name: 'Leg Press', sets: [{ weight: 20, reps: 12, done: true }, { weight: 20, reps: 12, done: true }, { weight: 20, reps: 12, done: true }] },
      { id: 'leg_extension', name: 'Leg Extension', sets: [{ weight: 35, reps: 12, done: true }, { weight: 35, reps: 12, done: true }, { weight: 35, reps: 12, done: true }] },
      { id: 'sumo_squats', name: 'Sumo Squats', sets: [{ weight: 7.5, reps: 12, done: true }, { weight: 7.5, reps: 12, done: true }] },
    ],
  },
  {
    date: '2026-05-28',
    dayKey: 'day4',
    completed: true,
    exercises: [
      { id: 'flat_db_press', name: 'Flat DB Press', sets: [{ weight: 5, reps: 10, done: true }, { weight: 7.5, reps: 10, done: true }, { weight: 10, reps: 10, done: true }] },
      { id: 'lat_pulldown_giant', name: 'Lats Pull Down', sets: [{ weight: 25, reps: 10, done: true }, { weight: 30, reps: 10, done: true }, { weight: 35, reps: 10, done: true }] },
      { id: 'shoulder_db_flys', name: 'Shoulder DB Flys', sets: [{ weight: 5, reps: 12, done: true }, { weight: 7.5, reps: 12, done: true }, { weight: 10, reps: 12, done: true }] },
      { id: 'bicep_curls_giant', name: 'Bicep Curls (Rod/DB/Cable)', sets: [{ weight: 5, reps: 12, done: true }, { weight: 7.5, reps: 12, done: true }, { weight: 10, reps: 12, done: true }] },
      { id: 'tricep_pressdown_giant', name: 'Triceps Press Down', sets: [{ weight: 0, reps: 12, done: true }, { weight: 0, reps: 12, done: true }, { weight: 0, reps: 12, done: true }] },
      { id: 'deadlift', name: 'Deadlift', sets: [{ weight: 2.5, reps: 8, done: true }, { weight: 5, reps: 8, done: true }, { weight: 7.5, reps: 8, done: true }] },
    ],
  },
]
